engines:
 phpcodesniffer:
  enabled: true
 #phpmd:
 # enabled: true
  #checks:
  # Design/TooManyPublicMethods:
   # enabled: false
ratings:
 paths:
 - protected/modules/install/**
 exclude_paths:
 - protected/modules/User/**